function plot_quad(h,traj,xBt,yBt,zBt,q,t)
  for m = 1:5:length(t)-1
    figure(h);
    clf
    hold on
    set(gcf,'defaultlinelinewidth',4);
    
    % Plot axes
    plot3([traj(1,m) traj(1,m)+zBt(1,m)],...
        [traj(2,m) traj(2,m)+zBt(2,m)],...
        [traj(3,m) traj(3,m)+zBt(3,m)],'K:')
    plot3([traj(1,m) traj(1,m)+xBt(1,m)],...
        [traj(2,m) traj(2,m)+xBt(2,m)],...
        [traj(3,m) traj(3,m)+xBt(3,m)],'K:')
    plot3([traj(1,m) traj(1,m)+yBt(1,m)],...
        [traj(2,m) traj(2,m)+yBt(2,m)],...
        [traj(3,m) traj(3,m)+yBt(3,m)],'K:')

    % Plot negative of xB and yB
    plot3([traj(1,m) traj(1,m)-xBt(1,m)],...
        [traj(2,m) traj(2,m)-xBt(2,m)],...
        [traj(3,m) traj(3,m)-xBt(3,m)],'K:')
    plot3([traj(1,m) traj(1,m)-yBt(1,m)],...
        [traj(2,m) traj(2,m)-yBt(2,m)],...
        [traj(3,m) traj(3,m)-yBt(3,m)],'K:')

    plot3([q(16,m) q(16,m)+q(13,m)],...
        [q(17,m) q(17,m)+q(14,m)],...
        [q(18,m) q(18,m)+q(15,m)],'K')
    plot3([q(16,m) q(16,m)+q(7,m)],...
        [q(17,m) q(17,m)+q(8,m)],...
        [q(18,m) q(18,m)+q(9,m)],'R')
    plot3([q(16,m) q(16,m)+q(10,m)],...
        [q(17,m) q(17,m)+q(11,m)],...
        [q(18,m) q(18,m)+q(12,m)],'B')
    plot3([q(16,m) q(16,m)-q(7,m)],...
        [q(17,m) q(17,m)-q(8,m)],...
        [q(18,m) q(18,m)-q(9,m)],'B')
    plot3([q(16,m) q(16,m)-q(10,m)],...
        [q(17,m) q(17,m)-q(11,m)],...
        [q(18,m) q(18,m)-q(12,m)],'B')
      
    % plot trajectory
    plot3(traj(1),traj(2),traj(3),'b-')
      
    axis([-3 6 -3 6 -3 3]);
    xlabel('X [m]');
    ylabel('Y [m]');
    zlabel('Z [m]');
    view(30,20);
    grid on;
    title('Simulated Minimum-Snap Trajectory Following');

    pause(0.01)
  end
  
  hold off
end